owner: getstreamline
repo: upptime

sites:
  - name: Streamline Landing
    url: https://www.getstreamline.com
  - name: Special Districts Backend
    url: https://production.getstreamline.net
  - name: System Catalog
    url: https://www.systemcatalog.net
  - name: Check My District
    url: https://www.checkmydistrict.org

status-website:
  cname: status.getstreamline.net
  baseUrl: ""
  logoUrl: https://raw.githubusercontent.com/getstreamline/upptime/refs/heads/master/assets/streamline-icon.png
  name: "Streamline"
  introTitle: "**Streamline** System Status"
  introMessage: Sitewide status can be found below. Updates regarding availablility will be posted here.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
